### ISSUE TITLE
Write more?

### ISSUE THREAD

**Issue by lasseborly** [Tahrima/blog#1]
Could you please maybe... write some more? :turtle:

**Comment by Tahrima** [comment]
Definitely! Just getting started, haha 
Thanks for making the theme, love it 

- Ema

**Comment by lasseborly** [comment]
I thought it was `anybodyhome` but I wasn't sure.
Like the modifications you had done to it.
Might have to revive it a bit and do some of the planned fixes on it.

Would you maybe want to help me a bit if you have gotten the time?

**Comment by Tahrima** [comment]
Thanks! I am interested in what you are planning to add/fix to the theme. :)
I was actually thinking about making my own sometime soon, so it would be great to help you out as a starter to that goal.

I'll contact you via email and we can figure out a way to chat!

**Comment by lasseborly** [comment]
Cool! I'll close :)
